### ISSUE TITLE
Compilation of 3.0 dev (r446) warning(s)

### ISSUE THREAD

**Issue by rwbc** [dsekercioglu/blackmarlin#35] opened 2021-12-18 12:24 UTC
While compiling 3.0dev a few times the last week recently it has this warning which looks a bit worrying?
(the other warnings are there since always AFAIK - mosty about unused imports/macros/variables)

The binary itself compiles fine.

```
warning: unreachable statement
   --> src\bm\bm_eval\evaluator.rs:384:9
    |
377 |               return Evaluation::new(self.nnue.feed_forward(board, 0) * turn + NNUE_TEMPO);
    |               ---------------------------------------------------------------------------- any code following this expression is unreachable
...
384 | /         let eval = self.evaluate_psqt(board, Piece::Pawn)
385 | |             + self.evaluate_psqt(board, Piece::Knight)
386 | |             + self.evaluate_psqt(board, Piece::Bishop)
387 | |             + self.evaluate_psqt(board, Piece::Rook)
...   |
391 | |             + self.evaluate_bishops(board)
392 | |             + self.evaluate_threats(board);
    | |___________________________________________^ unreachable statement
    |
    = note: `#[warn(unreachable_code)]` on by default
```

**Comment by dsekercioglu** [comment] 2021-12-18 21:34
The warning happened due to the early return condition when NNUE is enabled disabling all code after it which was the intended behavior. I now fixed all warnings for all 3 of the feature flags so they shouldn't be popping up anymore.

**Closed by dsekercioglu** 2021-12-18 21:34 UTC
